### ISSUE TITLE
Question regarding model checkpoints

### ISSUE THREAD

**Issue by anwai98** [mazurowski-lab/finetune-SAM#11]
Hi team,

Thanks for the really cool work, and also for open-sourcing your scripts.

I have a question: have you released the model checkpoints from your experiments (related to the different tasks performed for finetuning / self-supervised pretraining)? Maybe I totally overlooked it, I couldn't spot the download links. Would be happy to get access to them, if possible.

Thanks in advance!

**Comment by haoyudong-97** [comment]
We have the checkpoints for self-supervised pretraining at Step 3C (https://drive.google.com/drive/folders/1JAoy-Mh5QgxXsjWtQhMjOX16dN1kytLQ); we did not provide the checkpoints for self-supervised pertaining + fine-tuning since we have too many fine-tuning tasks.
