### ISSUE TITLE
multiple object in a same image

### ISSUE THREAD

**Issue by JaberAlNahian** [mazurowski-lab/finetune-SAM#13]
Thank you for your great work! I would like to know how this pipeline can segment multiple objects in a single image.

**Comment by Guhanxue** [comment]
do you mean multi-cls segmentation?

**Comment by JaberAlNahian** [comment]
Not really. I mean single class but multiple objects in an image. I am trying to segment wheat heads from an image. As there are multiple wheat heads in an image, I need to segment all the wheat heads.

**Comment by haoyudong-97** [comment]
I don't think you can segment multiple objects in an image w/ SAM. This is a problem rooted in SAM. In another paper (https://www.sciencedirect.com/science/article/pii/S1361841523001780) we test SAM on medical images and find that if we have prompts for one lung, it usually does not segment both lungs simultaneously.
