### ISSUE TITLE
Single image with multiple objects with different classes

### ISSUE THREAD

**Issue by itbear-shu** [mazurowski-lab/finetune-SAM#15]
How can I prepare the dataset when single image with multiple objects with different classes?

**Comment by Guhanxue** [comment]
Hi, for your dataset, you should prepare your masks as you would for any standard multi-class segmentation task, ensuring that each class is represented by distinct pixel values within the masks. Saying, pixels for object 1 are all represented by pixel value 1; pixels for object 2 are all represented by pixel value 2...
