### ISSUE TITLE
UnboundLocalError: local variable 'lr_' referenced before assignmen

### ISSUE THREAD

**Issue by Skwarson96** [mazurowski-lab/finetune-SAM#16]
Hello!
in SingleGPU_train_finetune_noprompt.py when argument if_warmup is False I get: `UnboundLocalError: local variable 'lr_' referenced before assignment` in 136 line [code](https://github.com/mazurowski-lab/finetune-SAM/blob/2e6574e32b8cb7d1437883b03cb2054e0c019118/SingleGPU_train_finetune_noprompt.py#L136). I thing variable `lr_` should have a value regardless of the argument if_warmup

Thanks for the great project!

**Comment by Guhanxue** [comment]
Hi, Thanks for pointing this out. This bug is fixed and please check our updated codes.
