### ISSUE TITLE
ddp train failed

### ISSUE THREAD

**Issue by ZHIZIHUABU** [mazurowski-lab/finetune-SAM#19]
when i use ddp_splitgpu_train_finetune_noprompt.py , the error raised, “all tensors to be on the same device,but found at least two devices,cuda:1 and cuda:0, how can i solve it.

**Comment by ZHIZIHUABU** [comment]
![Uploading Snipaste_2024-08-24_16-51-33.png…]()

**Comment by ZHIZIHUABU** [comment]
![Snipaste_2024-08-24_16-51-33](https://github.com/user-attachments/assets/edf8a6bd-70ef-40e8-a9e8-60f8ad159ad9)

**Comment by ZHIZIHUABU** [comment]
![Snipaste_2024-08-24_16-56-18](https://github.com/user-attachments/assets/bd7df803-3569-4b9c-aef0-44e0c974eb10)
i change the code

**Comment by Guhanxue** [comment]
Hi, sorry for the delay. May i ask if you solve the issue yet by changing the code? If not, i am glad to take a look to see what happens.

**Comment by haoyudong-97** [comment]
You can set args.device to [0] when using DDP. We set the default value to [0,1] to handle the case of using large models such as ViT-H, but running multi-gpus with DDP might some issues and we haven't optimized the code for that.
