### ISSUE TITLE
I don't find the args.encoder_adapter_depths  to be used in the all projects？

### ISSUE THREAD

**Issue by ShChen233** [mazurowski-lab/finetune-SAM#3]
```
args.if_mask_decoder_adapter=True
args.if_encoder_adapter=True
# You can pick the image encoder blocks by adding adapters
args.encoder_adapter_depths = range(0,12)
```

**Comment by Guhanxue** [comment]
Hi, i might not fully understand your question here. if you are using encoder_adapter_depth, it means you would like to use Adapter for fine-tune the model; thus for the other fine-tune methods such as only update decoder/ or use LoRA; this args.encoder_adapter_depths is not used. 

Also, for different Encoder architecture, you need to edit the args.encoder_adapter_depths accordingly, such as for vit-h, you need to do range(0,32).

If you are asking where in my piece of code i am referring to this args to add Adapters, it is in sam/modeling/image_encoder.py.
<img width="1022" alt="image" src="https://github.com/mazurowski-lab/finetune-SAM/assets/39239103/6b513b63-4d2d-4e92-834b-9bbabf5758d9">

Generally, it refers to the args.if_encoder_adapter and (self.depth in self.args.encoder_adapter_depths).

Please let me know if this answers your question, and feel free to add additional comments!!

**Comment by ShChen233** [comment]
Thank you very much!
