### ISSUE TITLE
Predict new unseen images without any labels

### ISSUE THREAD

**Issue by Gnkgo** [mazurowski-lab/finetune-SAM#7]
Hi there!

First of all, thanks for posting your code and giving such great instructions. It is easy to follow for a beginner!

Sorry if this question is too obvious, but I am new to the whole machine learning field.

But I don't understand how I can make my predictions on my dataset without labelled images? I trained the model on my images and got the best_checkpoint.pth. But I am not sure how to use this to actually make predictions?

Any answer is appreciated!

**Comment by Guhanxue** [comment]
Hi, I got your question here. are you saying directly inference the model without doing validation? i have that piece of code and i can share as jupyter notebook.

**Comment by Gnkgo** [comment]
Yes exactly, this would be much appreciated.

**Comment by Guhanxue** [comment]
Hi, I just updated two jupyter-notebook demos for making predictions and doing visualization. 1. 3D_predictions_with_vis.ipynb if for making predictions on an nifit image volume and 2.  2D_predictions_with_vis.ipynb is for making predictions on a .png image slice.

**Comment by Gnkgo** [comment]
Thank you so much!
